language: node_js
node_js:
  - "0.8"
env:
  global:
    # Sauce Labs are OK with this and it is currently necessary to expose this information for testing pull requests;
    # please get your own free key if you want to test yourself
    - SAUCE_USERNAME: intern-example-ci
    - SAUCE_ACCESS_KEY: 89ac3089-17b3-4e9b-aaf3-c475b27fa441
install:
  - git clone https://github.com/vladikoff/intern-examples
  - cd travis-ci-example
  - npm install intern
script: node node_modules/intern/runner.js config=tests/intern